sudo: required
services:
- docker
branches:
  only:
  - master
  - develop
  - /^v.*$/
  - feature/travis
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
before_install:
- docker build -t "ctpinstorecenter/commercetools-instore-center:${TRAVIS_COMMIT::8}" .
- docker tag "ctpinstorecenter/commercetools-instore-center:${TRAVIS_COMMIT::8}" "ctpinstorecenter/commercetools-instore-center:latest"
before_script:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script:
- ./travis-build.sh
after_script:
- docker logout
